# Generated by Django 3.0.8 on 2020-07-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
