# Generated by Django 3.0.8 on 2020-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home&Electronics', 'Home & Electronics'), ('FASHION', 'Fashion')], default='FASHION', max_length=20),
        ),
    ]
