# Generated by Django 3.0.8 on 2020-07-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOME&ELECTRONICS', 'Home & Electronics'), ('FASHION', 'Fashion')], default='FASHION', max_length=20),
        ),
    ]
