# Generated by Django 3.0.8 on 2020-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200728_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home & Electronics', 'Home & Electronics'), ('Fashion', 'Fashion')], default='FASHION', max_length=20),
        ),
    ]
